<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Categoria;

class CategoriaSeeder extends Seeder
{
    public function run(): void
    {
        Categoria::insert([

            [
                'id'=>1,
                'nome'=>'Oxalá',
                'descricao'=>'Orixá da criação, pureza e paz',
                'imagem'=>'https://i.pinimg.com/1200x/9e/71/72/9e71720c0e49d57ebd70c7748ffe1a75.jpg',
                'linha'=>'orixa',
                'cores'=>'Branco',
                'dia_semana'=>'Sexta-Feira',
                'historia'=>'Oxalá é considerado o pai de todos os orixás, símbolo da paz e da criação.',
                'simbolos'=>'Cajado, veste branca',
                'saudacoes'=>'Epa Baba!',
                'personalidade'=>'Calmo e justo',
                'animais'=>'Pombinha Branca',
                'elementos'=>'Ar',
                'datas_rituais'=>'21/12 - 25/12',
                'notas'=>'O sincretismo associa Oxalá a Jesus Cristo.',
                'created_at'=>now(),
                'updated_at'=>now()
            ],

            [
                'id'=>2,
                'nome'=>'Iemanjá',
                'descricao'=>'Orixá das águas, proteção e maternidade',
                'imagem'=>'https://i.pinimg.com/736x/ce/73/94/ce7394ba19e7a4cf1572ffc82ab865b9.jpg',
                'linha'=>'orixa',
                'cores'=>'Azul e branco',
                'dia_semana'=>'Sábado',
                'historia'=>'Iemanjá é a rainha do mar, mãe de todos os orixás e protetora dos pescadores.',
                'simbolos'=>'Conchas, colares',
                'saudacoes'=>'Odoya! Odocya!',
                'personalidade'=>'Mãe protetora',
                'animais'=>'Peixes, Golfinhos',
                'elementos'=>'Água',
                'datas_rituais'=>'02/02 - 08/12',
                'notas'=>'Associada a Nossa Senhora dos Navegantes.',
                'created_at'=>now(),
                'updated_at'=>now()
            ],

            [
                'id'=>3,
                'nome'=>'Ogum',
                'descricao'=>'Orixá da guerra e proteção',
                'imagem'=>'https://i.pinimg.com/control1/1200x/76/85/49/7685497c4e5d44903201692dbe048fee.jpg',
                'linha'=>'orixa',
                'cores'=>'Azul escuro e vermelho',
                'dia_semana'=>'Terça-feira',
                'historia'=>'Ogum é o guerreiro que abre caminhos.',
                'simbolos'=>'Espada, ferro',
                'saudacoes'=>'Ogunhê!',
                'personalidade'=>'Corajoso e direto',
                'animais'=>'Cão',
                'elementos'=>'Fogo',
                'datas_rituais'=>'23/04',
                'notas'=>'Associado a São Jorge.',
                'created_at'=>now(),
                'updated_at'=>now()
            ],
            [
            'id'=>4,
            'nome'=>'Xangô',
            'descricao'=>'Orixá da justiça e força',
            'imagem'=>'https://i.pinimg.com/1200x/f5/6f/26/f56f260c89be042963aee00ce3a2adf2.jpg',
            'linha'=>'orixa',
            'cores'=>'Vermelho e branco',
            'dia_semana'=>'Quarta-feira',
            'historia'=>'Xangô é o orixá da justiça e do fogo, senhor dos trovões e da força.',
            'simbolos'=>'Machado duplo, pedras',
            'saudacoes'=>'Kaô Kabecile!',
            'personalidade'=>'Justo e temperamental',
            'animais'=>'Leão',
            'elementos'=>'Fogo',
            'datas_rituais'=>'30/09',
            'notas'=>'Associado a São Jerônimo.',
            'created_at'=>now(),
            'updated_at'=>now()
            ],

            [
            'id'=>5,
            'nome'=>'Oxóssi',
            'descricao'=>'Orixá da caça e fartura',
            'imagem'=>'https://i.pinimg.com/1200x/f9/4c/00/f94c002b8e710425237972907d9d9d89.jpg',
            'linha'=>'orixa',
            'cores'=>'Verde',
            'dia_semana'=>'Quinta-feira',
            'historia'=>'Oxóssi é o guardião das matas e da fartura.',
            'simbolos'=>'Arco e flecha',
            'saudacoes'=>'Oke Aro!',
            'personalidade'=>'Sagaz e paciente',
            'animais'=>'Veado',
            'elementos'=>'Terra',
            'datas_rituais'=>'20/01',
            'notas'=>'Associado a São Sebastião.',
            'created_at'=>now(),
            'updated_at'=>now()
            ],

            [
            'id'=>6,
            'nome'=>'Caboclo',
            'descricao'=>'Espírito de proteção e sabedoria',
            'imagem'=>'https://i.pinimg.com/736x/c9/36/eb/c936eb95dd21daa45c49f3390f50ba1f.jpg',
            'linha'=>'linha',
            'cores'=>'Verde e marrom',
            'dia_semana'=>'Domingo',
            'historia'=>'Guias da natureza e cura.',
            'simbolos'=>'Facão, penas',
            'saudacoes'=>'Oke Arô!',
            'personalidade'=>'Sábio e protetor',
            'animais'=>'Onça',
            'elementos'=>'Terra',
            'datas_rituais'=>'15/08',
            'notas'=>null,
            'created_at'=>now(),
            'updated_at'=>now()
            ],

            [
            'id'=>7,
            'nome'=>'Preto-Velho',
            'descricao'=>'Espírito ancestral, conselheiro',
            'imagem'=>'https://i.pinimg.com/736x/25/0d/4a/250d4acfc0404033a8b4d4be13ee4c90.jpg',
            'linha'=>'linha',
            'cores'=>'Cinza',
            'dia_semana'=>'Sexta-feira',
            'historia'=>'Ancião que guia e aconselha.',
            'simbolos'=>'Cajado, charutos',
            'saudacoes'=>'Adorei as Almas!',
            'personalidade'=>'Calmo e experiente',
            'animais'=>'Coruja',
            'elementos'=>'Ar',
            'datas_rituais'=>'01/11',
            'notas'=>null,
            'created_at'=>now(),
            'updated_at'=>now()
            ],

            [
            'id'=>8,
            'nome'=>'Exu',
            'descricao'=>'Guardião dos caminhos e encruzilhadas',
            'imagem'=>'https://i.pinimg.com/736x/f4/ed/eb/f4edebbcf096ac24501fdda0b48cf3d8.jpg',
            'linha'=>'linha',
            'cores'=>'Vermelho e preto',
            'dia_semana'=>'Terça-feira',
            'historia'=>'Mensageiro e guardião de caminhos.',
            'simbolos'=>'Tridente, chaves',
            'saudacoes'=>'Laroiê!',
            'personalidade'=>'Astuto e rápido',
            'animais'=>'Cachorro',
            'elementos'=>'Fogo',
            'datas_rituais'=>'25/12',
            'notas'=>null,
            'created_at'=>now(),
            'updated_at'=>now()
            ],

            [
            'id'=>9,
            'nome'=>'Pomba Gira',
            'descricao'=>'Espírito feminino de força e sedução',
            'imagem'=>'https://i.pinimg.com/736x/b6/64/d0/b664d0a333e87a9a7ad8028c29aa9042.jpg',
            'linha'=>'linha',
            'cores'=>'Vermelho e rosa',
            'dia_semana'=>'Sábado',
            'historia'=>'Encanta e protege nos trabalhos amorosos.',
            'simbolos'=>'Espelhos, leques',
            'saudacoes'=>'Epa!',
            'personalidade'=>'Sensual e intensa',
            'animais'=>'Cavalo',
            'elementos'=>'Fogo',
            'datas_rituais'=>'31/12',
            'notas'=>null,
            'created_at'=>now(),
            'updated_at'=>now()
            ],
            [
            'id'=>10,
            'nome'=>'Ervas',
            'descricao'=>'Categoria destinada às ervas utilizadas em rituais e práticas espirituais.',
            'imagem'=>'https://i.pinimg.com/1200x/a2/28/f5/a228f571ac9c3d36955fcdf24d234a1f.jpg',
            'linha'=>'Itens',
            'cores'=>'verde, marrom',
            'dia_semana'=>'segunda-feira',
            'historia'=>'Ervas usadas tradicionalmente para proteção, limpeza e energização.',
            'simbolos'=>'folhas, raízes',
            'saudacoes'=>'Saudações às ervas',
            'personalidade'=>'Calma, purificação',
            'animais'=>'Coruja, cervo',
            'elementos'=>'Terra, água',
            'datas_rituais'=>'1º de cada mês',
            'notas'=>'Algumas notas sobre uso e procedência das ervas',
            'created_at'=>now(),
            'updated_at'=>now()
            ],

            [
            'id'=>11,
            'nome'=>'Pedras',
            'descricao'=>'Categoria destinada às pedras utilizadas em rituais e práticas espirituais.',
            'imagem'=>'https://i.pinimg.com/736x/39/8c/86/398c869811287b3e132e22dbf4f70d30.jpg',
            'linha'=>'Itens',
            'cores'=>'diversas',
            'dia_semana'=>'segunda-feira',
            'historia'=>'Pedras usadas tradicionalmente para proteção, limpeza e energização.',
            'simbolos'=>'Cristais, geodos',
            'saudacoes'=>'Saudações às pedras',
            'personalidade'=>'Equilíbrio, energia positiva',
            'animais'=>'Leão, coruja',
            'elementos'=>'Terra, fogo',
            'datas_rituais'=>'1º de cada mês',
            'notas'=>'Algumas notas sobre uso e procedência das pedras',
            'created_at'=>now(),
            'updated_at'=>now()
            ],

            [
            'id'=>12,
            'nome'=>'Iansã',
            'descricao'=>'Orixá dos ventos e tempestades, senhora da energia',
            'imagem'=>'https://i.pinimg.com/736x/10/e9/67/10e967205a8071cc194330e00340cf8c.jpg',
            'linha'=>'orixa',
            'cores'=>'Vermelho e marrom',
            'dia_semana'=>'Quarta-feira',
            'historia'=>'Iansã é senhora dos ventos e tempestades, ligada à transformação e coragem.',
            'simbolos'=>'Espada, chifres de boi',
            'saudacoes'=>'Eparrey!',
            'personalidade'=>'Corajosa e independente',
            'animais'=>'Cavalo',
            'elementos'=>'Ar',
            'datas_rituais'=>'04/12',
            'notas'=>'Orixá associado à transformação.',
            'created_at'=>now(),
            'updated_at'=>now()
            ],

            [
            'id'=>23,
            'nome'=>'Obaluaê/Omulu',
            'descricao'=>'Orixá da saúde, cura e transformação',
            'imagem'=>'https://i.pinimg.com/736x/29/db/c9/29dbc94fb3bf76ce0511538b637552ff.jpg',
            'linha'=>'orixa',
            'cores'=>'Branco e marrom',
            'dia_semana'=>'Segunda-feira',
            'historia'=>'Protetor da saúde e doenças.',
            'simbolos'=>'Capa de palha, cajado',
            'saudacoes'=>'Atoto!',
            'personalidade'=>'Paciente e curador',
            'animais'=>'Rato',
            'elementos'=>'Terra',
            'datas_rituais'=>'13/08',
            'notas'=>'Associado a São Lázaro e São Roque.',
            'created_at'=>now(),
            'updated_at'=>now()
            ],

            [
            'id'=>24,
            'nome'=>'Nanã',
            'descricao'=>'Orixá das águas paradas e ancestralidade',
            'imagem'=>'https://i.pinimg.com/1200x/e7/75/86/e77586517f7523fb1c7cf9c3c285a0fc.jpg',
            'linha'=>'orixa',
            'cores'=>'Lilás e roxo',
            'dia_semana'=>'Terça-feira',
            'historia'=>'Representa ancestralidade, sabedoria e equilíbrio.',
            'simbolos'=>'Cajado, cabaça',
            'saudacoes'=>'Saluba Nanã!',
            'personalidade'=>'Sábia e reflexiva',
            'animais'=>'Jacaré',
            'elementos'=>'Água',
            'datas_rituais'=>'26/07',
            'notas'=>'Associada a Santa Sant’Ana.',
            'created_at'=>now(),
            'updated_at'=>now()
            ],

            [
            'id'=>25,
            'nome'=>'Oxumaré',
            'descricao'=>'Orixá da riqueza e movimento',
            'imagem'=>'https://i.pinimg.com/1200x/4a/47/a8/4a47a82d0d2372aa4c40db4901d09fad.jpg',
            'linha'=>'orixa',
            'cores'=>'Verde e amarelo',
            'dia_semana'=>'Terça-feira',
            'historia'=>'Orixá da serpente e do arco-íris, símbolo de renovação.',
            'simbolos'=>'Serpente, arco-íris',
            'saudacoes'=>'Arroboboi!',
            'personalidade'=>'Flexível e renovador',
            'animais'=>'Serpente',
            'elementos'=>'Ar/Terra',
            'datas_rituais'=>'24/08',
            'notas'=>'Associado a São Bartolomeu.',
            'created_at'=>now(),
            'updated_at'=>now()
            ],
            [
            'id'=>27,
            'nome'=>'Erê',
            'descricao'=>'Espírito infantil de alegria e brincadeira',
            'imagem'=>'https://i.pinimg.com/1200x/07/61/74/076174a542dc05c0b69aa5d9a76d8494.jpg',
            'linha'=>'linha',
            'cores'=>'Colorido',
            'dia_semana'=>'Sábado',
            'historia'=>'Espírito infantil que traz leveza, alegria e proteção.',
            'simbolos'=>'Brinquedos, doces',
            'saudacoes'=>'Salve as Crianças!',
            'personalidade'=>'Brincalhão e travesso',
            'animais'=>'Criança',
            'elementos'=>'Ar',
            'datas_rituais'=>'01/01',
            'notas'=>null,
            'created_at'=>now(),
            'updated_at'=>now()
            ],

            [
            'id'=>28,
            'nome'=>'Baiano',
            'descricao'=>'Espírito de força, proteção e sabedoria',
            'imagem'=>'https://i.pinimg.com/736x/ce/74/02/ce7402662a44e0ff922e6a912084668f.jpg',
            'linha'=>'linha',
            'cores'=>'Azul e branco',
            'dia_semana'=>'Domingo',
            'historia'=>'Guias que trazem proteção e força nos trabalhos espirituais.',
            'simbolos'=>'Facão, tambor',
            'saudacoes'=>'Epa!',
            'personalidade'=>'Corajoso e alegre',
            'animais'=>'Cavalo',
            'elementos'=>'Terra',
            'datas_rituais'=>'02/07',
            'notas'=>null,
            'created_at'=>now(),
            'updated_at'=>now()
            ],

            [
            'id'=>29,
            'nome'=>'Marinheiro',
            'descricao'=>'Espírito ligado ao mar e viagens',
            'imagem'=>'https://i.pinimg.com/1200x/51/d2/e8/51d2e8b2bc9aaf4fda6f1f2b97f498d8.jpg',
            'linha'=>'linha',
            'cores'=>'Azul',
            'dia_semana'=>'Sábado',
            'historia'=>'Guia protetor das viagens e do mar.',
            'simbolos'=>'Âncora, corda',
            'saudacoes'=>'Laroiê!',
            'personalidade'=>'Aventureiro e protetor',
            'animais'=>'Golfinho',
            'elementos'=>'Água',
            'datas_rituais'=>'20/08',
            'notas'=>null,
            'created_at'=>now(),
            'updated_at'=>now()
            ],

            [
            'id'=>30,
            'nome'=>'Cigano',
            'descricao'=>'Espírito da liberdade e alegria',
            'imagem'=>'https://i.pinimg.com/736x/56/4e/52/564e52fa5578d308e9dfdb170798e679.jpg',
            'linha'=>'linha',
            'cores'=>'Vermelho e dourado',
            'dia_semana'=>'Sexta-feira',
            'historia'=>'Guias que trazem alegria, sorte e dança.',
            'simbolos'=>'Cartas, lenços coloridos',
            'saudacoes'=>'Optcha!',
            'personalidade'=>'Sociável e alegre',
            'animais'=>'Cavalo',
            'elementos'=>'Fogo',
            'datas_rituais'=>'05/09',
            'notas'=>null,
            'created_at'=>now(),
            'updated_at'=>now()
            ],

            [
            'id'=>31,
            'nome'=>'Oxum',
            'descricao'=>'Orixá do amor, da fertilidade e das águas doces',
            'imagem'=>'https://i.pinimg.com/736x/b9/d6/73/b9d673dca9f8f3c257b6dbaa70030bf6.jpg',
            'linha'=>'orixa',
            'cores'=>'Amarelo e dourado',
            'dia_semana'=>'Sábado',
            'historia'=>'Oxum representa beleza, amor, fertilidade e prosperidade.',
            'simbolos'=>'Espelhos, leques, pulseiras douradas',
            'saudacoes'=>'Oraieieo!',
            'personalidade'=>'Carinhosa e vaidosa',
            'animais'=>'Peixes, Cisnes',
            'elementos'=>'Água',
            'datas_rituais'=>'08/12',
            'notas'=>'Associada a Nossa Senhora da Conceição.',
            'created_at'=>now(),
            'updated_at'=>now()
],
        ]);
    }
}