<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdutoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $produtos = [
            [
                'id'           => 1,
                'nome'         => 'Velas de Oxalá',
                'descricao'    => 'Velas brancas para oferenda',
                'preco'        => 15.00,
                'imagem'       => 'https://http2.mlstatic.com/D_NQ_NP_804876-MLB78358727185_082024-O-vela-palito-n-2-maco-c-8-unidades-branca-12g-c-nfe.webp',
                'categoria_id' => 1,
                'created_at'   => '2025-09-22 13:25:11',
                'updated_at'   => '2025-09-23 21:48:45',
                'estoque'      => 20,
                'codigo'       => 'VXO001',
                'peso'         => 0.20,
                'dimensoes'    => '10x3 cm',
                'tags'         => 'vela,oxala,oferta',
                'popular'      => 1,
                'ativo'        => 1,
                'observacoes'  => null,
            ],
            [
                'id'           => 2,
                'nome'         => 'Estátua de Ogum',
                'descricao'    => 'Estátua para altar de Ogum',
                'preco'        => 120.00,
                'imagem'       => 'https://i.pinimg.com/736x/e1/87/99/e18799dcb410a70b268cd60097a68cd2.jpg',
                'categoria_id' => 3,
                'created_at'   => '2025-09-22 13:25:11',
                'updated_at'   => '2025-09-23 22:30:31',
                'estoque'      => 5,
                'codigo'       => 'ESTO001',
                'peso'         => 1.50,
                'dimensoes'    => '20x10x10 cm',
                'tags'         => 'estatua,ogum',
                'popular'      => 1,
                'ativo'        => 1,
                'observacoes'  => null,
            ],
            [
                'id'           => 3,
                'nome'         => 'Imagem de Iemanjá',
                'descricao'    => 'Imagem da orixá Iemanjá',
                'preco'        => 80.00,
                'imagem'       => 'https://i.pinimg.com/736x/23/36/01/23360118eaf87734c544ccec61a62a33.jpg',
                'categoria_id' => 2,
                'created_at'   => '2025-09-22 13:25:11',
                'updated_at'   => '2025-09-23 22:37:24',
                'estoque'      => 10,
                'codigo'       => 'IMG001',
                'peso'         => 0.80,
                'dimensoes'    => '15x10x5 cm',
                'tags'         => 'imagem,iemanja',
                'popular'      => 1,
                'ativo'        => 1,
                'observacoes'  => null,
            ],
            [
                'id'           => 4,
                'nome'         => 'Amuleto de Oxóssi',
                'descricao'    => 'Amuleto protetor',
                'preco'        => 25.00,
                'imagem'       => 'https://lista.mercadolivre.com.br/patua-de-orixas',
                'categoria_id' => 5,
                'created_at'   => '2025-09-22 13:25:11',
                'updated_at'   => '2025-09-22 13:25:11',
                'estoque'      => 30,
                'codigo'       => 'PAT001',
                'peso'         => 0.10,
                'dimensoes'    => '5x5 cm',
                'tags'         => 'amulet,oxossi',
                'popular'      => 1,
                'ativo'        => 1,
                'observacoes'  => '',
            ],
            [
                'id'           => 5,
                'nome'         => 'Guias de Caboclo',
                'descricao'    => 'Colares para trabalhos espirituais',
                'preco'        => 30.00,
                'imagem'       => 'https://i.pinimg.com/control1/736x/23/14/a9/2314a9c0cf78ae5ce3dfeb650f786164.jpg',
                'categoria_id' => 6,
                'created_at'   => '2025-09-22 13:25:11',
                'updated_at'   => '2025-09-22 13:25:11',
                'estoque'      => 15,
                'codigo'       => 'GUIA001',
                'peso'         => 0.30,
                'dimensoes'    => '15 cm',
                'tags'         => 'guia,caboclo',
                'popular'      => 1,
                'ativo'        => 1,
                'observacoes'  => '',
            ],
            [
                'id'           => 6,
                'nome'         => 'Velas de Preto-Velho',
                'descricao'    => 'Velas para oferendas e proteção',
                'preco'        => 12.00,
                'imagem'       => 'https://i.pinimg.com/1200x/83/fd/9a/83fd9aa6058457eef4f768d0e6bc1f83.jpg',
                'categoria_id' => 7,
                'created_at'   => '2025-09-22 13:25:11',
                'updated_at'   => '2025-09-22 13:25:11',
                'estoque'      => 25,
                'codigo'       => 'VPH001',
                'peso'         => 0.20,
                'dimensoes'    => '10x3 cm',
                'tags'         => 'vela,preto-velho',
                'popular'      => 1,
                'ativo'        => 1,
                'observacoes'  => '',
            ],
            [
                'id'           => 7,
                'nome'         => 'Estátua de Exu',
                'descricao'    => 'Estátua protetora',
                'preco'        => 100.00,
                'imagem'       => 'https://i.pinimg.com/736x/d9/38/ea/d938ea6b1999beaf6a3fdde393136d38.jpg',
                'categoria_id' => 8,
                'created_at'   => '2025-09-22 13:25:11',
                'updated_at'   => '2025-09-22 13:25:11',
                'estoque'      => 7,
                'codigo'       => 'ESTEX001',
                'peso'         => 1.20,
                'dimensoes'    => '18x10x10 cm',
                'tags'         => 'estatua,exu',
                'popular'      => 1,
                'ativo'        => 1,
                'observacoes'  => '',
            ],
            [
                'id'           => 8,
                'nome'         => 'Guias de Pomba Gira',
                'descricao'    => 'Colares para trabalhos espirituais',
                'preco'        => 35.00,
                'imagem'       => 'https://i.pinimg.com/1200x/b8/b8/16/b8b8168da1213e19ae1c7737dd664179.jpg',
                'categoria_id' => 9,
                'created_at'   => '2025-09-22 13:25:11',
                'updated_at'   => '2025-09-22 13:25:11',
                'estoque'      => 12,
                'codigo'       => 'GUIAPG001',
                'peso'         => 0.40,
                'dimensoes'    => '15 cm',
                'tags'         => 'guia,pomba-gira',
                'popular'      => 1,
                'ativo'        => 1,
                'observacoes'  => '',
            ],
            [
                'id'           => 9,
                'nome'         => 'Arruda',
                'descricao'    => 'Erva de proteção e limpeza espiritual.',
                'preco'        => 5.50,
                'imagem'       => 'https://i.pinimg.com/control1/1200x/cd/7f/ff/cd7fffe1618f62bf83cfbdf19c66d8c3.jpg',
                'categoria_id' => 10,
                'created_at'   => '2025-09-22 14:50:10',
                'updated_at'   => '2025-09-22 14:50:10',
                'estoque'      => 50,
                'codigo'       => 'ERV001',
                'peso'         => 0.05,
                'dimensoes'    => '10x5x2 cm',
                'tags'         => 'protecao,limpeza',
                'popular'      => 1,
                'ativo'        => 1,
                'observacoes'  => 'Uso em banhos e amuletos',
            ],
            [
                'id'           => 10,
                'nome'         => 'Manjericão',
                'descricao'    => 'Erva para prosperidade e equilíbrio.',
                'preco'        => 6.00,
                'imagem'       => 'https://i.pinimg.com/736x/5b/81/69/5b8169d3d62992eb2e35f67c9b570fc8.jpg',
                'categoria_id' => 10,
                'created_at'   => '2025-09-22 14:50:10',
                'updated_at'   => '2025-09-22 14:50:10',
                'estoque'      => 40,
                'codigo'       => 'ERV002',
                'peso'         => 0.05,
                'dimensoes'    => '10x5x2 cm',
                'tags'         => 'prosperidade,harmonia',
                'popular'      => 1,
                'ativo'        => 1,
                'observacoes'  => 'Pode ser usada em rituais ou incensos',
            ],
            [
                'id'           => 11,
                'nome'         => 'Hortelã',
                'descricao'    => 'Erva para limpeza e energização.',
                'preco'        => 4.50,
                'imagem'       => 'https://i.pinimg.com/736x/63/44/a1/6344a16ff1c74e0c9083ee6f21969440.jpg',
                'categoria_id' => 10,
                'created_at'   => '2025-09-22 14:50:10',
                'updated_at'   => '2025-09-22 14:50:10',
                'estoque'      => 60,
                'codigo'       => 'ERV003',
                'peso'         => 0.05,
                'dimensoes'    => '10x5x2 cm',
                'tags'         => 'purificacao,energia',
                'popular'      => 1,
                'ativo'        => 1,
                'observacoes'  => 'Uso em banhos, chás e rituais',
            ],
            [
                'id'           => 12,
                'nome'         => 'Alecrim',
                'descricao'    => 'Erva de proteção e purificação.',
                'preco'        => 5.00,
                'imagem'       => 'https://exemplo.com/alecrim.jpg',
                'categoria_id' => 10,
                'created_at'   => '2025-09-22 14:50:10',
                'updated_at'   => '2025-09-22 14:50:10',
                'estoque'      => 45,
                'codigo'       => 'ERV004',
                'peso'         => 0.05,
                'dimensoes'    => '10x5x2 cm',
                'tags'         => 'protecao,energia',
                'popular'      => 1,
                'ativo'        => 1,
                'observacoes'  => 'Pode ser usada em banhos e defumações',
            ],
            [
                'id'           => 13,
                'nome'         => 'Camomila',
                'descricao'    => 'Erva calmante e harmonizadora.',
                'preco'        => 4.80,
                'imagem'       => 'https://exemplo.com/camomila.jpg',
                'categoria_id' => 10,
                'created_at'   => '2025-09-22 14:50:10',
                'updated_at'   => '2025-09-22 14:50:10',
                'estoque'      => 50,
                'codigo'       => 'ERV005',
                'peso'         => 0.05,
                'dimensoes'    => '10x5x2 cm',
                'tags'         => 'calma,energia',
                'popular'      => 1,
                'ativo'        => 1,
                'observacoes'  => 'Uso em chás e rituais',
            ],
            [
                'id'           => 14,
                'nome'         => 'Ametista',
                'descricao'    => 'Cristal violeta de equilíbrio e proteção.',
                'preco'        => 15.00,
                'imagem'       => 'https://exemplo.com/ametista.jpg',
                'categoria_id' => 11,
                'created_at'   => '2025-09-22 14:50:10',
                'updated_at'   => '2025-09-22 14:50:10',
                'estoque'      => 25,
                'codigo'       => 'PED001',
                'peso'         => 0.10,
                'dimensoes'    => '4x4x4 cm',
                'tags'         => 'equilibrio,protecao',
                'popular'      => 1,
                'ativo'        => 1,
                'observacoes'  => 'Pode ser usada em anéis, colares ou altar',
            ],
            [
                'id'           => 15,
                'nome'         => 'Quartzo Rosa',
                'descricao'    => 'Pedra do amor e harmonia.',
                'preco'        => 18.00,
                'imagem'       => 'https://exemplo.com/quartzo_rosa.jpg',
                'categoria_id' => 11,
                'created_at'   => '2025-09-22 14:50:10',
                'updated_at'   => '2025-09-22 14:50:10',
                'estoque'      => 20,
                'codigo'       => 'PED002',
                'peso'         => 0.10,
                'dimensoes'    => '4x4x4 cm',
                'tags'         => 'amor,harmonia',
                'popular'      => 1,
                'ativo'        => 1,
                'observacoes'  => 'Uso em rituais de amor e proteção',
            ],
            [
                'id'           => 16,
                'nome'         => 'Citrino',
                'descricao'    => 'Pedra da prosperidade e energia positiva.',
                'preco'        => 20.00,
                'imagem'       => 'https://exemplo.com/citrino.jpg',
                'categoria_id' => 11,
                'created_at'   => '2025-09-22 14:50:10',
                'updated_at'   => '2025-09-22 14:50:10',
                'estoque'      => 15,
                'codigo'       => 'PED003',
                'peso'         => 0.12,
                'dimensoes'    => '5x5x5 cm',
                'tags'         => 'prosperidade,energia',
                'popular'      => 1,
                'ativo'        => 1,
                'observacoes'  => 'Pode ser usado em altar ou colar',
            ],
            [
                'id'           => 17,
                'nome'         => 'Jade',
                'descricao'    => 'Pedra da harmonia e equilíbrio.',
                'preco'        => 22.00,
                'imagem'       => 'https://exemplo.com/jade.jpg',
                'categoria_id' => 11,
                'created_at'   => '2025-09-22 14:50:10',
                'updated_at'   => '2025-09-22 14:50:10',
                'estoque'      => 18,
                'codigo'       => 'PED004',
                'peso'         => 0.12,
                'dimensoes'    => '5x5x5 cm',
                'tags'         => 'harmonia,equilibrio',
                'popular'      => 1,
                'ativo'        => 1,
                'observacoes'  => 'Ideal para meditação ou colares',
            ],
            [
                'id'           => 18,
                'nome'         => 'Turmalina Negra',
                'descricao'    => 'Pedra de proteção energética.',
                'preco'        => 25.00,
                'imagem'       => 'https://exemplo.com/turmalina_negra.jpg',
                'categoria_id' => 11,
                'created_at'   => '2025-09-22 14:50:10',
                'updated_at'   => '2025-09-22 14:50:10',
                'estoque'      => 12,
                'codigo'       => 'PED005',
                'peso'         => 0.15,
                'dimensoes'    => '6x6x6 cm',
                'tags'         => 'protecao,energia',
                'popular'      => 1,
                'ativo'        => 1,
                'observacoes'  => 'Colocar em ambientes ou altar',
            ],
        ];

        DB::table('produtos')->insert($produtos);
    }
}